---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generateName: vnf-reference-
spec:
  instancetype:
    name: n1.large
  preference:
    name: rhel.9
  running: true
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        generateName: vnf-reference-
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  template:
    spec:
      domain:
        devices:
          interfaces:
          - masquerade: {}
            name: pod
#          - sriov: {}
#            name: vf0
      volumes:
      - dataVolume: {}
        name: boot
      - cloudInitNoCloud:
          userData: |
            #!/bin/sh

            echo 'printed from cloud-init userdata'
        name: cloudinit
      networks:
      - name: pod
        pod: {}
#      - name: vf0
#        multus:
#          networkName: node0-vf0
